[package]
name = "arkyo"
license = "MIT"
edition = "2021"
version = "0.0.5"
authors = ["DhavyLTS"]
description = "arkyo is a library for making HTTP Server"

[dependencies]
chrono = "0.4.34"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
